" Define our mapleader
:let mapleader = ","

" Easy access to this file and easy sourcing
map <leader>vm :find $MYVIMRC<CR>
map <leader>s :source $MYVIMRC<CR>

set nocompatible

syntax on

source ~/.vim/configs/base.vim
source ~/.vim/configs/plugins.vim
source ~/.vim/configs/bindings.vim

" Look for local vim config options for this machine
if filereadable(expand("~/.vimrc.local"))
	source ~/.vimrc.local
endif

filetype plugin indent on
